name: Deploy Shiny App to ShinyApps.io

on:
  push:
    branches:
      - yechan  # 푸시할 branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub Repository Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # 3. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    # 4. Debug Secrets
    - name: Debug Secrets
      run: |
        echo "RSCONNECT_USER: $RSCONNECT_USER"
        echo "RSCONNECT_TOKEN: $RSCONNECT_TOKEN"
        echo "RSCONNECT_SECRET: $RSCONNECT_SECRET"

    # 5. Install rsconnect package
    - name: Install rsconnect package
      run: |
        Rscript -e "install.packages('rsconnect', repos='http://cran.r-project.org')"

    # 6. Deploy Shiny App with forceUpdate
    - name: Deploy Shiny App
      run: |
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('RSCONNECT_USER'), token=Sys.getenv('RSCONNECT_TOKEN'), secret=Sys.getenv('RSCONNECT_SECRET'))"
        Rscript -e "rsconnect::deployApp(forceUpdate = TRUE)"
