name: Deploy Shiny App to ShinyApps.io

on:
  push:
    branches:
      - yechan  # yechan 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the GitHub Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up R environment
    - name: Set up R 4.3.1
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    # 3. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    # 4. Install required R packages
    - name: Install required R packages
      run: |
        Rscript -e "install.packages(c('shiny', 'httpuv', 'htmltools', 'rsconnect'), repos='http://cran.r-project.org')"


    # 5. Deploy Shiny App
    - name: Deploy Shiny App
      env:
        RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
        RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
        RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      run: |
        echo "Deploying Shiny App"
        Rscript -e "renv::snapshot(confirm = TRUE)"
        Rscript -e "renv::restore()"       
        Rscript -e "renv::dependencies()"  
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('RSCONNECT_USER'), token=Sys.getenv('RSCONNECT_TOKEN'), secret=Sys.getenv('RSCONNECT_SECRET'))"
        Rscript -e "rsconnect::deployApp(appDir = './', forceUpdate = TRUE)"
