name: Deploy Shiny App to ShinyApps.io

on:
  push:
    branches:
      - yechan  # yechan 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the GitHub Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up R environment
    - name: Set up R 4.3.1
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    # 3. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    # 4. Cache R packages
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/R
        key: ${{ runner.os }}-R-packages-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-R-packages-
          
    # 5. Install required R packages
    - name: Install required R packages
      run: |
        Rscript -e "if (!requireNamespace('shiny')) install.packages(c('shiny', 'httpuv', 'rmarkdown', 'knitr', 'jsonlite', 'htmltools', 'reticulate', 'rsconnect'), repos='http://cran.r-project.org')"

    # 6. Deploy Shiny App
    - name: Deploy Shiny App
      env:
        RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
        RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
        RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      run: |
        echo "Deploying Shiny App"
        Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('RSCONNECT_USER'), token=Sys.getenv('RSCONNECT_TOKEN'), secret=Sys.getenv('RSCONNECT_SECRET'))"
        Rscript -e "rsconnect::deployApp(appDir = './Exploratory_Data_Analysis-Final_project/', forceUpdate = TRUE)"
